name: Add to Kanban Project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue/PR to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/FinalTaxReturn/projects/3
          github-token: ${{ secrets.PROJECT_PERSONAL_ACCESS_TOKEN }}
